### ISSUE TITLE
Group4: ToDo List

### ISSUE THREAD

**Issue by WalterAlvar** [HackYourFutureBelgium/class-15#281]
# Group 4

- @yildiztugba : _contributor_
- @danielhalasz  : _contributor_
- @deepa-thomas : _contributor_
- @WalterAlvar  : _repository owner_

## The Project
We decide to create a simple __"To Do List"__ app which allow you to add, remove and sort items.

### Check list

- [ ] [repo](https://github.com/WalterAlvar/separation-of-concerns-starter) (with a complete README)
- [ ] [live demo](https://walteralvar.github.io/separation-of-concerns-starter/)
- [planning](https://github.com/WalterAlvar/separation-of-concerns-starter/tree/master/planning)
  - [ ] communication plan
  - [ ] constraints
  - [ ] backlog
  - [ ] wireframe
  - [ ] development strategy
  - [ ] retrospective
- [ ] [project board](https://github.com/WalterAlvar/separation-of-concerns-starter/projects)

**Comment by samirm00** [comment]
Wow the Demo looks great! Well done!

**Comment by samirm00** [comment]
Very good project and well done!
Maybe a few things to make even better 

1- naming variables :  like   `const newLi,   const cb´ those are really bad names ,  maybe `const  newTodoItem` is much better at least it give us an idea what it means.
2- remove all commented code , you just don't need it 
3- remove  console.log 

But , you have done a very good job :)

**Comment by samirm00** [comment]
Hello there,
Very good project.
However, the `select` and ` edit` and `delete one todo`  are non functional
