### ISSUE TITLE
Michael: , number of weeks in this module

### ISSUE THREAD

**Issue by Mika215** [HackYourFutureBelgium/class-15#306]
> [module repository](https://github.com/Mika215/architecture/tree/master/function-roles)

## Study Plan

- [x] [Intro to Architecture](https://vimeo.com/593884915) - abstraction! layers!

- examples
  - [x] 🥚 [/function-roles](https://github.com/Mika215/architecture/tree/master/function-roles): learn about the function roles you will be using in this module
  - [ ] 🥚 [/stepped](https://github.com/Mika215/architecture/tree/master/stepped): study HTML/CSS/JS projects built up step-by-step (only examples)
  - [ ] 🥚 [/separated](https://github.com/Mika215/architecture/tree/master/separated): study HTML/CSS/JS projects that have been separated by concern (only examples)
- exercises
  - [ ] 🐣 [/json-schemas](https://github.com/Mika215/architecture/tree/master/json-schemas): learn to describe JS data using a _schema_, and how to validate data against a schema.

**Comment by Mika215** [comment]
Week 1

- [ ] started the exercises
- [ ] [project issue - Group-4](https://github.com/HackYourFutureBelgium/class-15/issues/292)

### Check-In

#### I Need Help With:

#### What went well?
- reviewing the video recordings  

#### What went less well
  - Time management, group project and group communications(things didn't went as i have planned)

#### Lessons Learned
- i would like to apologize for my delayed check in 

### Sunday Prep Work

**Comment by Mika215** [comment]
Week 2

- [ ] started the exercises
- [ ] [project issue - Group-4](https://github.com/HackYourFutureBelgium/class-15/issues/292)

### Check-In

#### I Need Help With:

#### What went well?
- reviewing the video recordings  

#### What went less well
  - Time management, group project and group communications(things didn't went as i have planned),

#### Lessons Learned
- This module  is a bit hard compared to the previous modules that we have had before. I am trying to cope up with the times i have missed in the past week and these two days.  

### Sunday Prep Work

**Comment by colevandersWands** [comment]
@Mika215 , maybe try getting in touch with @Moamin-AbuEwaida.  He was also having trouble finding his way through this module's examples but has started to figure it out.  He may have some tips for you

**Comment by Mika215** [comment]
OK,I'll read over the examples and I will also ask help from Moamine for some advices from his experience.
Thanks @colevandersWands

**Comment by Mika215** [comment]
### Week 2

- [ ] started the exercises
- [ ] [project issue - Group-4](https://github.com/HackYourFutureBelgium/class-15/issues/292)

### Check-In

#### I Need Help With:

#### What went well?
- 

#### What went less well
  -

#### Lessons Learned
-  It is really shame!  but i have to admit the fact that i have totally failed in this module. May be it could be  a lesson for the upcoming modules(not making same mistakes with self organization and time management). 

### Sunday Prep Work
